#!/bin/bash

echo "=== 跑马灯作品集测试 ==="
echo ""
echo "请打开以下链接测试跑马灯效果："
echo ""
echo "1. 跑马灯视图: http://localhost:8080/portfolio/marquee/"
echo "   - 动态滚动的项目展示"
echo "   - 鼠标悬停暂停滚动"
echo "   - 卡片悬停放大效果"
echo ""
echo "2. 网格视图: http://localhost:8080/portfolio/"
echo "   - 传统的网格布局"
echo "   - 包含切换到跑马灯视图的按钮"
echo ""
echo "3. 首页: http://localhost:8080/"
echo "   - 查看整体网站效果"
echo ""
echo "=== 功能说明 ==="
echo ""
echo "跑马灯功能："
echo "1. 自动滚动：卡片从左向右无限循环滚动"
echo "2. 悬停暂停：鼠标悬停在跑马灯区域时暂停滚动"
echo "3. 卡片交互："
echo "   - 鼠标悬停在轨道上：所有卡片模糊缩小"
echo "   - 鼠标悬停在单个卡片上：该卡片清晰放大"
echo "4. 点击跳转：点击卡片跳转到项目详情页"
echo ""
echo "=== 设计特点 ==="
echo ""
echo "1. 视觉效果："
echo "   - 毛玻璃效果背景"
echo "   - 渐变边框"
echo "   - 平滑动画过渡"
echo "2. 响应式设计："
echo "   - 桌面端：卡片宽度320px"
echo "   - 平板端：卡片宽度250px"
echo "   - 手机端：卡片宽度200px"
echo "3. 性能优化："
echo "   - 图片懒加载"
echo "   - CSS动画（无JavaScript依赖）"
echo "   - 硬件加速变换"
echo ""
echo "=== 数据源 ==="
echo ""
echo "项目数据来自：data/portfolio.yml"
echo "包含6个项目，每个项目有："
echo "- 标题 (title)"
echo "- 图片 (image)"
echo "- 链接 (url)"
echo "- 类型 (type)"
echo "- 图标 (icon)"
echo ""
echo "=== 故障排除 ==="
echo ""
echo "如果跑马灯不工作："
echo "1. 检查浏览器是否支持CSS动画"
echo "2. 检查控制台是否有错误（按F12）"
echo "3. 确保data/portfolio.yml文件存在且格式正确"
echo "4. 检查图片文件路径是否正确"