#!/bin/bash

echo "=== 测试视频背景 ==="
echo ""
echo "请打开以下链接测试视频背景："
echo ""
echo "1. 最小视频测试: http://localhost:8080/video-minimal.html"
echo "   - 最简单的视频测试页面"
echo "   - 视频应该全屏显示，有绿色边框"
echo ""
echo "2. 视频控制测试: http://localhost:8080/video-simple-test.html"
echo "   - 带控制按钮的视频测试"
echo "   - 可以测试播放、暂停等功能"
echo ""
echo "3. 多视频对比测试: http://localhost:8080/test-video-direct.html"
echo "   - 测试所有视频文件"
echo "   - 显示加载状态"
echo ""
echo "4. 智能车项目页面: http://localhost:8080/projects/smart-car/"
echo "   - 实际的智能车项目页面"
echo "   - 视频应该作为背景显示"
echo "   - 视频有红色调试边框"
echo ""
echo "5. 直接访问视频文件: http://localhost:8080/videos/smart-car-fixed.mp4"
echo "   - 直接访问视频文件"
echo ""
echo "=== 故障排除 ==="
echo ""
echo "如果视频不显示，请检查："
echo "1. 浏览器控制台是否有错误（按F12）"
echo "2. 网络标签页中视频文件是否成功加载"
echo "3. 视频元素是否在DOM中（检查元素）"
echo "4. 视频元素的样式是否正确应用"
echo ""
echo "=== 视频文件信息 ==="
echo ""
ls -la public/videos/*.mp4 | awk '{print $9, "大小:", $5/1024/1024 "MB"}'
echo ""
echo "视频海报: public/videos/smart-car-poster.jpg"