#!/bin/bash

echo "=== 简洁跑马灯作品集测试 ==="
echo ""
echo "访问链接: http://localhost:8080/portfolio/"
echo ""
echo "设计特点:"
echo "1. 简洁专业 - 只展示实际的两个项目"
echo "2. 文字清晰 - 添加渐变遮罩，文字不被遮挡"
echo "3. 纯跑马灯 - 没有切换按钮，直接展示"
echo "4. 响应式设计 - 适配各种屏幕尺寸"
echo ""
echo "功能说明:"
echo "• 自动滚动: 30秒完成一次循环"
echo "• 悬停暂停: 鼠标悬停在跑马灯区域暂停"
echo "• 卡片交互: 悬停在单个卡片上放大突出"
echo "• 点击跳转: 点击卡片查看项目详情"
echo ""
echo "项目展示:"
echo "1. 6-DOF Underwater Robot"
echo "   - 图片: /images/portfolio/underwater-robot.jpg"
echo "   - 链接: /projects/underwater-robot/"
echo "   - 标签: ROS2, Mujoco, PPO算法, PID控制"
echo ""
echo "2. 智能车竞赛"
echo "   - 图片: /images/portfolio/smart-car-competition.jpg"
echo "   - 链接: /projects/smart-car/"
echo "   - 标签: Ubuntu, 八邻域算法, YOLO, PID控制"
echo ""
echo "技术实现:"
echo "• 纯CSS动画，无JavaScript依赖"
echo "• 毛玻璃效果背景"
echo "• 渐变遮罩防止文字遮挡"
echo "• 硬件加速变换优化性能"
echo ""
echo "如果页面不显示或有问题，请检查:"
echo "1. 浏览器控制台错误 (按F12)"
echo "2. 图片文件路径是否正确"
echo "3. 数据文件格式是否正确"